# Generated by Django 3.2.7 on 2021-10-04 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(choices=[('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold')], default='B', max_length=1)),
                ('work_type', models.CharField(choices=[('P', 'Pickup'), ('D', 'Delivery'), ('A', 'Both')], default='P', max_length=1)),
                ('nid', models.CharField(max_length=30)),
                ('points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('registration_date', models.DateTimeField(auto_now=True)),
                ('nid_front', models.URLField(blank=True, null=True)),
                ('nid_back', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='area.hub')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.deliveryman')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(choices=[('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold')], default='B', max_length=1)),
                ('nid', models.CharField(max_length=30)),
                ('nid_front', models.URLField(blank=True, null=True)),
                ('nid_back', models.URLField(blank=True, null=True)),
                ('points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('registration_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
