# Generated by Django 3.2.8 on 2021-10-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211006_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryman',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
