# Generated by Django 3.2.7 on 2021-10-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('phone_no', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Assigned'), ('K', 'Picked'), ('C', 'Canceled'), ('R', 'In Transit')], default='P', max_length=1)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_charge', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cod_fee', models.DecimalField(decimal_places=2, max_digits=4)),
                ('discounts', models.DecimalField(decimal_places=2, max_digits=4)),
                ('additional_charge', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('issue_status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=1)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('issue_response', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(blank=True, max_length=10, null=True)),
                ('creationDate', models.DateTimeField(auto_now=True)),
                ('receiver_name', models.CharField(max_length=50)),
                ('collection_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customer_address', models.CharField(max_length=100)),
                ('item_description', models.CharField(blank=True, max_length=100, null=True)),
                ('item_weight', models.CharField(default='1KG', max_length=50)),
                ('instruction', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['creationDate'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('delivery_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('inprocess', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('processed', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='PickupAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('store_code', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('facebook', models.URLField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
