# Generated by Django 3.2.7 on 2021-10-04 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('parcels', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='profiles.merchant'),
        ),
        migrations.AddField(
            model_name='pickupaddress',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='area.area'),
        ),
        migrations.AddField(
            model_name='pickupaddress',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.store'),
        ),
        migrations.AddField(
            model_name='payment',
            name='merchant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.merchant'),
        ),
        migrations.AddField(
            model_name='parcelorder',
            name='customer_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='area.area'),
        ),
        migrations.AddField(
            model_name='parcelorder',
            name='customer_phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='parcels.customerinfo'),
        ),
        migrations.AddField(
            model_name='parcelorder',
            name='delivery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcels.deliverytype'),
        ),
        migrations.AddField(
            model_name='parcelorder',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcels.itemtype'),
        ),
        migrations.AddField(
            model_name='parcelorder',
            name='pickup_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='parcels.pickupaddress'),
        ),
        migrations.AddField(
            model_name='parcelorder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_orders', to='parcels.store'),
        ),
        migrations.AddField(
            model_name='parcelissue',
            name='issue_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='parcels.parcelorder'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.merchant'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='Parcel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parcels.parcelorder'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='current_hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_deliveries', to='area.hub'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='deliveryman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='profiles.deliveryman'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='destination_hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='area.hub'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickupman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to='profiles.deliveryman'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='merchant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.merchant'),
        ),
    ]
