# Generated by Django 3.2.7 on 2021-10-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='ordercost',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='parcels.parcelorder'),
            preserve_default=False,
        ),
    ]
