# Generated by Django 3.2.7 on 2021-10-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_rename_parcel_delivery_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
