# Generated by Django 3.2.7 on 2021-10-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0005_invoice_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='status',
            new_name='pickup_status',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('N', 'No Data'), ('T', 'In Transit'), ('D', 'Assigned'), ('X', 'Returning'), ('H', 'Complete')], default='N', max_length=1),
        ),
    ]
