# Generated by Django 3.2.7 on 2021-10-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0006_auto_20211005_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='pickup_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Assigned'), ('K', 'Picked'), ('C', 'Canceled'), ('R', 'Received')], default='P', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='parcelorder',
            unique_together={('parcel_id', 'customer_phone')},
        ),
    ]
