# Generated by Django 3.2.8 on 2021-10-06 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0008_customerinfo_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parcelorder',
            unique_together=set(),
        ),
    ]
