# Generated by Django 3.2.8 on 2021-10-07 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('parcels', '0009_alter_parcelorder_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='current_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stored_deliveries', to='area.hub'),
        ),
    ]
